[technote]
id = "RTN-087"
series_id = "RTN"
canonical_url = "https://rtn-087.lsst.io"
github_url = "https://github.com/lsst/rtn-087"
github_default_branch = "main"
date_created = 2024-08-22T21:29:11Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "stable"

[[technote.authors]]
name.given = "Diane"
name.family = "Hascall"
internal_id = "hascalld"

[[technote.authors.affiliations]]
name = "SLAC National Accelerator Laboratory"
internal_id = "SLAC"
address = "2575 Sand Hill Rd., Menlo Park, CA 94025, USA"
