[technote]
id = "RTN-087"
series_id = "RTN"
canonical_url = "https://rtn-087.lsst.io"
github_url = "https://github.com/lsst/rtn-087"
github_default_branch = "main"
date_created = 2024-08-22T21:29:11Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "Matthew R."
name.family = "Rumore"
internal_id = "rumoremr"

[[technote.authors.affiliations]]
name = "Brookhaven National Laboratory"
internal_id = "BNL"
address = "Upton, NY 11973, USA"
